# Generated by Django 3.2.7 on 2021-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='datetime')),
                ('tweets', models.PositiveIntegerField()),
                ('following', models.PositiveIntegerField()),
                ('followers', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('media', models.PositiveIntegerField()),
                ('protected', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('favourites_count', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('profile_banner_url', models.CharField(max_length=100)),
                ('profile_image_url_https', models.CharField(max_length=100)),
                ('default_profile_image', models.BooleanField()),
                ('withheld_in_countries', models.CharField(max_length=10)),
            ],
        ),
    ]
