# Generated by Django 4.0.4 on 2022-04-13 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterComments',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author_screen_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=2500)),
                ('hashtags', models.JSONField(null=True)),
                ('urls', models.JSONField(null=True)),
                ('likes_count', models.IntegerField(null=True)),
                ('retweets_count', models.IntegerField(null=True)),
                ('comments_to_comments', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'twitter_comments',
            },
        ),
        migrations.CreateModel(
            name='TwitterTweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.CharField(max_length=2500)),
                ('lang', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('author_id', models.BigIntegerField(default=0)),
                ('author_screen_name', models.CharField(default='', max_length=50)),
                ('reply_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('retweet_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('quote_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('original_screen_name', models.CharField(blank=True, max_length=50, null=True)),
                ('retweet_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('retweet_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('urls', models.JSONField(null=True)),
                ('user_mentions', models.JSONField(null=True)),
                ('coordinates', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'twitter_tweet',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('twitter_url', models.CharField(blank=True, default='undefined', max_length=100, null=True)),
                ('profile_image_url', models.CharField(blank=True, default='undefined', max_length=250)),
                ('description', models.CharField(blank=True, default='undefined', max_length=2500, null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('description_urls', models.JSONField(null=True)),
                ('birthday', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('web', models.CharField(blank=True, default='undefined', max_length=300, null=True)),
                ('location', models.CharField(blank=True, default='undefined', max_length=100, null=True)),
                ('category', models.CharField(blank=True, default='undefined', max_length=200, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('friends_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('statuses_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('listed_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'twitter_user',
            },
        ),
        migrations.CreateModel(
            name='TwitterRelations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('follower_id', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteruser')),
            ],
            options={
                'db_table': 'twitter_relations',
                'unique_together': {('user_id', 'follower_id')},
            },
        ),
    ]
