# Generated by Django 3.2.13 on 2022-05-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='twitterlikes',
            table='twitter_likes',
        ),
    ]
