# Generated by Django 4.0.4 on 2022-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_alter_twitteruser_birthday_alter_twitteruser_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=160)),
                ('user_id', models.BigIntegerField(null=True)),
                ('liked_user', models.CharField(max_length=160)),
                ('liked_user_id', models.BigIntegerField(null=True)),
                ('tweet_text', models.CharField(max_length=300)),
                ('tweet_hashtags', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
