# Generated by Django 4.0.4 on 2022-04-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twitterlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterlikes',
            name='tweet_links',
            field=models.URLField(null=True),
        ),
    ]
