# Generated by Django 4.0.4 on 2022-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_twitterlikes_tweet_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlikes',
            name='tweet_links',
            field=models.JSONField(null=True),
        ),
    ]
