# Generated by Django 3.2.7 on 2022-01-15 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20211011_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'twitter_relations',
            },
        ),
        migrations.CreateModel(
            name='TwitterTweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.CharField(max_length=500)),
                ('lang', models.CharField(max_length=10)),
                ('retweet_count', models.IntegerField(blank=True, default=0, null=True)),
                ('favorite_count', models.IntegerField(blank=True, default=0, null=True)),
                ('hashtags', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('urls', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('user_mentions', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('coordinates', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('source', models.CharField(max_length=50)),
                ('tweet_type', models.CharField(max_length=30)),
                ('media', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('original_screen_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'twitter_tweet',
            },
        ),
        migrations.CreateModel(
            name='TwitterUserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('profile_image_url', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=160, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('followers_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('friends_count', models.IntegerField(blank=True, default=0, null=True)),
                ('favourites_count', models.IntegerField(blank=True, default=0, null=True)),
                ('statuses_count', models.IntegerField(blank=True, default=0, null=True)),
                ('listed_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'twitter_userInfo',
            },
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteruserinfo'),
        ),
        migrations.AddField(
            model_name='twitterrelations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteruserinfo'),
        ),
    ]
