# Generated by Django 4.0.4 on 2022-04-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_alter_twitterlikes_tweet_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterlikes',
            name='user_id',
        ),
    ]
