# Generated by Django 4.0.4 on 2022-04-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_remove_twitterlikes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlikes',
            name='liked_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
