# Generated by Django 3.2.7 on 2022-01-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_alter_twitterrelations_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterrelations',
            name='id',
        ),
        migrations.AlterField(
            model_name='twitterrelations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='twitter.twitteruserinfo'),
        ),
    ]
