# Generated by Django 3.2.7 on 2022-01-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20220115_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterRelations',
        ),
    ]
