# Generated by Django 3.2.7 on 2022-01-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_twitterrelations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterrelations',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteruserinfo'),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteruserinfo'),
        ),
    ]
