# Generated by Django 3.2.7 on 2022-01-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_auto_20220115_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterrelations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
