# Generated by Django 3.2.7 on 2022-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0014_auto_20220115_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='favourites_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='followers_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='friends_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='listed_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='profile_image_url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='statuses_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
