# Generated by Django 3.2.7 on 2022-01-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0017_auto_20220117_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='description',
            field=models.CharField(blank=True, default='undefined', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='location',
            field=models.CharField(blank=True, default='undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='profile_image_url',
            field=models.CharField(blank=True, default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='url',
            field=models.CharField(blank=True, default='undefined', max_length=50, null=True),
        ),
    ]
