# Generated by Django 4.0.4 on 2022-04-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0020_alter_twitteruserinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashtags_chain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('mode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTweetsStatistics',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='twitter.twitteruserinfo')),
                ('week_time_activity', models.JSONField()),
                ('date_activity', models.JSONField()),
                ('week_activity', models.JSONField()),
                ('devices', models.JSONField()),
                ('url_mentions', models.JSONField(null=True)),
                ('user_mentions', models.JSONField(null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('quotes', models.JSONField(null=True)),
                ('type_tweets', models.JSONField()),
                ('retweets', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'twitter_tweetsstat',
            },
        ),
    ]
