# Generated by Django 4.0.4 on 2022-04-13 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0021_hashtags_chain_twittertweetsstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterComments',
            fields=[
                ('author_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author_screen_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=2500)),
                ('hashtags', models.JSONField(null=True)),
                ('urls', models.JSONField(null=True)),
                ('likes_count', models.IntegerField(null=True)),
                ('retweets_count', models.IntegerField(null=True)),
                ('comments_to_comments', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'twitter_comments',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('twitter_url', models.CharField(blank=True, default='undefined', max_length=50, null=True)),
                ('profile_image_url', models.CharField(blank=True, default='undefined', max_length=100)),
                ('description', models.CharField(blank=True, default='undefined', max_length=160, null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('birthday', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('web', models.CharField(blank=True, default='undefined', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='undefined', max_length=50, null=True)),
                ('category', models.CharField(blank=True, default='undefined', max_length=50, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('friends_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('favourites_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('statuses_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('listed_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'twitter_user',
            },
        ),
        migrations.RenameModel(
            old_name='hashtags_chain',
            new_name='TwitterHashtags',
        ),
        migrations.RenameField(
            model_name='twittertweet',
            old_name='favorite_count',
            new_name='comments_count',
        ),
        migrations.RenameField(
            model_name='twittertweet',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='twittertweet',
            name='media',
        ),
        migrations.RemoveField(
            model_name='twittertweet',
            name='tweet_type',
        ),
        migrations.RemoveField(
            model_name='twittertweet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='twitterrelations',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='author_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='author_screen_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='likes_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='quote_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='reply_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='retweet_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='twittertweet',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='coordinates',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='hashtags',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='text',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='urls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='user_mentions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterModelTable(
            name='twitterhashtags',
            table='twitter_hashtags',
        ),
        migrations.DeleteModel(
            name='TwitterTweetsStatistics',
        ),
        migrations.AlterField(
            model_name='twitterrelations',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='twitter.twitteruser'),
        ),
        migrations.DeleteModel(
            name='TwitterUserInfo',
        ),
    ]
