# Generated by Django 4.0.4 on 2022-04-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0022_twittercomments_twitteruser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittertweet',
            name='comments_count',
        ),
    ]
