# Generated by Django 4.0.4 on 2022-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0023_remove_twittertweet_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittertweet',
            name='retweet_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
