# Generated by Django 4.0.4 on 2022-04-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0024_twittertweet_retweet_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterHashtags',
        ),
    ]
