# Generated by Django 4.0.4 on 2022-04-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0025_delete_twitterhashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='twitteruser',
            old_name='favourites_count',
            new_name='likes_count',
        ),
    ]
