# Generated by Django 4.0.4 on 2022-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0026_rename_created_at_twitteruser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='description_urls',
            field=models.JSONField(null=True),
        ),
    ]
