# Generated by Django 4.0.4 on 2022-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0027_twitteruser_description_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='category',
            field=models.CharField(blank=True, default='undefined', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='description',
            field=models.CharField(blank=True, default='undefined', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='location',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='profile_image_url',
            field=models.CharField(blank=True, default='undefined', max_length=250),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='screen_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_url',
            field=models.CharField(blank=True, default='undefined', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='web',
            field=models.CharField(blank=True, default='undefined', max_length=300, null=True),
        ),
    ]
