# Generated by Django 3.2.13 on 2022-04-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0028_alter_twitteruser_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterHashtags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag_value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'twitter_hashtags',
            },
        ),
    ]
