# Generated by Django 3.2.13 on 2022-04-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0029_twitterhashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterLikes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=160)),
                ('liked_user', models.CharField(max_length=160)),
                ('liked_user_id', models.IntegerField(null=True)),
                ('tweet_text', models.CharField(max_length=300)),
                ('tweet_hashtags', models.JSONField(null=True)),
                ('tweet_links', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
