# Generated by Django 3.2.13 on 2022-04-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0031_alter_twitterlikes_liked_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPersons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_screen_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'twitter_persons',
            },
        ),
    ]
