# Generated by Django 3.2.7 on 2021-09-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourites_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='listed_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='media',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_banner_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url_https',
        ),
        migrations.RemoveField(
            model_name='user',
            name='protected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='statuses_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tweets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='withheld_in_countries',
        ),
    ]
