# Generated by Django 3.2.7 on 2021-10-11 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0003_auto_20211005_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='TwitterUser',
        ),
    ]
