# Generated by Django 3.2.7 on 2022-01-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0005_auto_20220115_0721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='twitterrelations',
            unique_together={('user_id', 'follower_id')},
        ),
    ]
