# Generated by Django 3.2.7 on 2022-01-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0012_auto_20220115_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertweet',
            name='favorite_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twittertweet',
            name='retweet_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='favourites_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='followers_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='friends_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='listed_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='statuses_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
