# Generated by Django 3.2.7 on 2022-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0015_auto_20220115_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
