# Generated by Django 3.2.7 on 2022-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0016_auto_20220115_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruserinfo',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
