# Generated by Django 3.2.7 on 2022-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osiris', '0018_auto_20220117_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertweet',
            name='original_screen_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
