# Generated by Django 3.2.13 on 2022-05-02 11:02

from django.db import migrations, models
import django.utils.timezone
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'хештег',
                'verbose_name_plural': 'Список хештегов',
                'db_table': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=160)),
                ('liked_text', models.CharField(max_length=300)),
                ('hashtags', models.JSONField(null=True)),
                ('urls', models.JSONField(null=True)),
                ('liked_user', models.CharField(max_length=160)),
                ('liked_user_id', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'db_table': 'likes',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('likes'), models.Model),
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Список профилей',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author_id', models.BigIntegerField(default=0)),
                ('author_screen_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('text', models.CharField(max_length=2500)),
                ('hashtags', models.JSONField(null=True)),
                ('urls', models.JSONField(null=True)),
                ('likes_count', models.BigIntegerField(null=True)),
                ('retweet_count', models.BigIntegerField(null=True)),
                ('quote_count', models.BigIntegerField(null=True)),
                ('reply_count', models.BigIntegerField(null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'replies',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('replies'), models.Model),
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('text', models.CharField(max_length=2500)),
                ('lang', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('author_id', models.BigIntegerField(default=0)),
                ('author_screen_name', models.CharField(default='', max_length=50)),
                ('replys_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('retweets_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('quotes_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('source_author', models.CharField(blank=True, max_length=50, null=True)),
                ('source_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('source_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('urls', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Твит',
                'verbose_name_plural': 'Твиты',
                'db_table': 'tweets',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('tweets'), models.Model),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('twitter_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('profile_image_url', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('hashtags', models.JSONField(null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('web', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('birthday', models.DateTimeField()),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateTimeField()),
                ('followers_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('friends_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('statuses_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('listed_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('users'), models.Model),
        ),
    ]
