# Generated by Django 3.2.13 on 2022-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_rename_replys_count_tweets_replies_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='author_screen_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='source_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
