# Generated by Django 3.2.13 on 2022-05-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='replys_count',
            new_name='replies_count',
        ),
    ]
