# Generated by Django 3.2.13 on 2022-05-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0003_auto_20220502_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='quote_count',
            new_name='quotes_count',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='reply_count',
            new_name='replies_count',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='retweet_count',
            new_name='retweets_count',
        ),
    ]
