# Generated by Django 3.2.13 on 2022-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_hfile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfile',
            name='imageUrl',
            field=models.FileField(blank=True, null=True, upload_to='./backend/static/'),
        ),
    ]
